Feature/private blobs
krismichalski/carrierwave-azure_rm pull request #2
Opened 2017-04-18 16:33 UTC by stestaub

This feature allows carrierwave-azure_rm to automatically sign the returned urls if the accesspolicy of the blobs is set to private. This makes it easy to handle private files on azure

2017-04-19 17:14 UTC, ghost requested changes
Hi! Thank you for your second contribution!
I reviewed your changes and noticed a small typo in README.

Also, I have few questions regarding SharedAccessSignature, especially its expire time. Could you have a look?

Everything else looks good, so after we resolve these problems I can accept your pull request and release a new version.

2017-04-19 17:14 UTC, ghost commented on README.md
> +config.public_access_level = 'priavte' # optional - possible values are blob, private, container
Typo, should be:  `config.public_access_level = 'private'`

2017-04-19 17:14 UTC, ghost commented on lib/carrierwave/storage/azure_rm.rb
> +          ::Azure::Storage::Core::Auth::SharedAccessSignature.new
Shouldn't we specify when this token will expire?
Like for example here: https://github.com/supportify/paperclip-azure/blob/master/lib/paperclip/storage/azure.rb#L74

2017-04-19 17:14 UTC, ghost commented on lib/carrierwave/storage/azure_rm.rb
> +          ::Azure::Storage::Core::Auth::SharedAccessSignature.new
And we could have an option for how long token is valid. Something like `add_config :token_expire_after`. What do you think?

2017-04-19 17:14 UTC, nooulaif commented on lib/carrierwave/storage/azure_rm.rb
> +          ::Azure::Storage::Core::Auth::SharedAccessSignature.new
Wouldn't it be better for `store!` method to have write permission, and `retrieve!` to have only read permission?

2017-04-24 09:00 UTC, stestaub commented
Thank you for your feedback. I added the expiry explicitly and used add_config to overwrite the default value. The access signature is actually only used for the `#url` method where I already set the permission to read only. Methods as store! and delete go through the `Azure::Storage::Blob::BlobService` so there is no need for the SAS.

2017-04-24 12:12 UTC, nooulaif commented
I see.
Thank you, excellent work! 
Gonna merge and release a new version immediately.

2017-04-24 12:12 UTC, ghost approved these changes

2017-04-24 12:13 UTC, merged